server.tomcat.accesslog.enabled=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true

spring.datasource.url=jdbc:postgresql://backend_tg_spring_boot_schedule_bot_user:z90CXasOBjjnLqospt428jBXnjxgHUaO@dpg-crjf5jtumphs73d02ljg-a/backend_tg_spring_boot_schedule_bot
spring.datasource.username=backend_tg_spring_boot_schedule_bot_user
spring.datasource.password=z90CXasOBjjnLqospt428jBXnjxgHUaO
spring.datasource.driver-class-name=org.postgresql.Driver

telegrambot.userName=@schedule_bot
telegrambot.botToken=5874204988:AAGSrcOIsbM4P78RxZepAwyaOqSopIpACeg
telegrambot.webHookPath=https://backend-tg-spring-boot-schedule-bot.onrender.com

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
